### ISSUE TITLE
remove delay to give the browser time to finish write

### ISSUE THREAD

**Issue by koen1711** [leaphy-robotics/avrdude-webassembly#2]
There is an very ugly delay to give the browser time here, which needs to be fixed.
https://github.com/leaphy-robotics/avrdude-webassembly/blob/6f1a210aa955da73ed402bbb3725a25e55c25db5/libserial/LibSerial.cpp#L176

**Comment by rmoesbergen** [comment]
Emscripten bug report: https://github.com/emscripten-core/emscripten/issues/21581

**Comment by sverben** [comment]
he joch, fix het nou
